cursor                  {cursor}
cursor_text_color       {background}

background              #000000
foreground              {color15}
selection_foreground    {background}
selection_background    {color4}
url_color               {color4}

#: black 000000 767676
color0  {color0}
color8  {color8}
#: red cc0403 f2201f
color1  {color1}
color9  {color9}
#: green 19cb00 23fd00
color2  {color2}
color10 {color10}
#: yellow cecb00 fffd00
color3  {color3}
color11 {color11}
#: blue 0d73cc 1a8fff
color4  {color4}
color12 {color12}
#: magenta cb1ed1 fd28ff
color5  {color5}
color13 {color13}
#: cyan 0dcdcd 14ffff
color6  {color6}
color14 {color14}
#: white dddddd ffffff
color7  {color7}
color15 {color15}

active_tab_foreground   {background}
inactive_tab_foreground {color4}
inactive_tab_background {background}

active_border_color     {color4}
inactive_border_color   {background}
# bell_border_color     #ff5a00
