# User environment variables
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
export EDITOR=nvim
export GTK_CSD=0

# Auto launch sway
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    export XDG_SESSION_TYPE=wayland
    export XDG_CURRENT_DESKTOP=sway
    exec sway
fi
