# Blur Settings
for_window [class=".*"] blur enable
for_window [class=".*"] opacity 0.88
for_window [class=".*"] dim_inactive 0.2
for_window [class=".*"] blur_saturation 1.1
for_window [class=".*"] blur_contrast 1.5
for_window [class=".*"] blur_radius 10

# Layer shell Settings
layer_effects "rofi" {
    blur enable;
    corner_radius 11;
}

layer_effects "swayosd" {
    blur enable;
    corner_radius 7;
}
