# Colors
set $white #c7c7c7
set $dim-white #454545
set $black #000000
set $red #e02b2b

# target                 title    bg      text    indicator  border
client.focused           $black   $black  $black  $white     $white
client.focused_inactive  $black   $black  $black  $dim-white $dim-white
client.unfocused         $black   $black  $black  $dim-white $dim-white
client.urgent            $black   $black  $black  $red       $red
