# Colors
set $fg #7aa2f7
set $fg-faded #454545
set $nil #000000
set $red #e02b2b

# target                 title  bg     text   indicator   border
client.focused           $nil   $nil   $nil   $fg         $fg
client.focused_inactive  $nil   $nil   $nil   $fg-faded   $fg-faded
client.unfocused         $nil   $nil   $nil   $fg-faded   $fg-faded
client.urgent            $nil   $nil   $nil   $red        $red
