############################## Touchpad ############################## 
#Essential settings
input type:touchpad {
      dwt enabled                    #Disable while typing
      tap enabled
      natural_scroll enabled
      middle_emulation enabled       #Three finger tap = middle click
      tap_button_map lrm             #Multiple button support, sigle tap meaning left click, double finger tap meaning right click, and so on...
      scroll_factor 0.7
  }

#Workspace swipe settings
bindgesture swipe:3:right exec ~/Scripts/sway/3finger_swipe.sh prev
bindgesture swipe:3:left exec ~/Scripts/sway/3finger_swipe.sh next
