hide_window_decorations yes
enable_audio_bell no
font_family      family="CaskaydiaCove Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11
window_padding_width 10
touch-scroll_multiplier 12.0
