#!/usr/bin/env bash

#check if vscode is running
if pgrep -x "code" >/dev/null; then
  echo "VS Code is currently running. Please close it before updating."
  exit 1
fi

#find user's package manager
if command -v apt-get &>/dev/null; then
  echo "Distro detected: Debian based"
  INSTALL_CMD="sudo apt-get install -y"
elif command -v dnf &>/dev/null; then
  echo "Distro detected: Fedora based"
  INSTALL_CMD="sudo dnf install -y"
elif command -v yum &>/dev/null; then
  echo "Distro detected: RHEL/CentOS based"
  INSTALL_CMD="sudo yum install -y"
elif command -v pacman &>/dev/null; then
  echo "Distro detected: Arch based"
  INSTALL_CMD="sudo pacman -S --noconfirm"
elif command -v apk &>/dev/null; then
  echo "Distro detected: Alpine based"
  INSTALL_CMD="sudo apk add"
elif command -v xbps-install &>/dev/null; then
  echo "Distro detected: Void based"
  INSTALL_CMD="sudo xbps-install -Sy"
else
  echo "Error: No supported package manager found."
  exit 1
fi
#check if aria2 is installed
if command -v aria2c &>/dev/null; then
  pkg_is_installed="0"
else
  pkg_is_installed="1"
  echo "aria2 not installed, installing now."
fi
# install package incase its not installed
if [ "$pkg_is_installed" -ne 0 ]; then
  $INSTALL_CMD aria2
fi

#installation directory
install_dir="/home/$USER/Applications/Gui"
mkdir -p "$install_dir" # Creates the path if it doesn't exist
#installing vscode
aria2c -d /tmp/ -o vscode-linux.tar.gz -x 16 -s 16 -k 1M 'https://code.visualstudio.com/sha/download?build=stable&os=linux-x64'
#handle Backup (only if the VSCode folder exists)
if [ -d "$install_dir/VSCode" ]; then
  rm -rf "$install_dir/VSCodeBAK"
  mv "$install_dir/VSCode" "$install_dir/VSCodeBAK"
fi
#move the extracted file to appropriate directory and clean up
mkdir -p "$install_dir/VSCode"
tar -xvf /tmp/vscode-linux.tar.gz -C "$install_dir/VSCode" --strip-components=1
rm -f /tmp/vscode-linux.tar.gz
