#!/usr/bin/env bash

#check if aria2 is installed
aria2c -v &>/dev/null
if [ $? -eq 0 ]; then
  is_installed="0"
  echo "starting..."
else
  is_installed="1"
  echo "aria2 not installed, installing now."
fi
#find user's package manager
if command -v apt-get &>/dev/null; then
  echo "Distro detected: Debian based"
  INSTALL_CMD="sudo apt-get install -y"
elif command -v dnf &>/dev/null; then
  echo "Distro detected: Fedora based"
  INSTALL_CMD="sudo dnf install -y"
elif command -v yum &>/dev/null; then
  echo "Distro detected: RHEL/CentOS based"
  INSTALL_CMD="sudo yum install -y"
elif command -v pacman &>/dev/null; then
  echo "Distro detected: Arch based"
  INSTALL_CMD="sudo pacman -S --noconfirm"
elif command -v apk &>/dev/null; then
  echo "Distro detected: Alpine based"
  INSTALL_CMD="sudo apk add"
elif command -v xbps-install &>/dev/null; then
  echo "Distro detected: Void based"
  INSTALL_CMD="sudo xbps-install -Sy"
else
  echo "Error: No supported package manager found."
  exit 1
fi
# install package incase its not installed
if [ "$is_installed" -ne 0 ]; then
  $INSTALL_CMD aria2
fi

aria2c -x 16 -s 16 -k 1M 'https://code.visualstudio.com/sha/download?build=stable&os=linux-x64'
