#!/usr/bin/env bash

#find user's package manager
if command -v apt-get &>/dev/null; then
  echo "Distro detected: Debian based"
  INSTALL_CMD="sudo apt-get install -y"
elif command -v dnf &>/dev/null; then
  echo "Distro detected: Fedora based"
  INSTALL_CMD="sudo dnf install -y"
elif command -v yum &>/dev/null; then
  echo "Distro detected: RHEL/CentOS based"
  INSTALL_CMD="sudo yum install -y"
elif command -v pacman &>/dev/null; then
  echo "Distro detected: Arch based"
  INSTALL_CMD="sudo pacman -S --noconfirm"
elif command -v apk &>/dev/null; then
  echo "Distro detected: Alpine based"
  INSTALL_CMD="sudo apk add"
elif command -v xbps-install &>/dev/null; then
  echo "Distro detected: Void based"
  INSTALL_CMD="sudo xbps-install -Sy"
else
  echo "Error: No supported package manager found."
  exit 1
fi
#check if aria2 & 7z is installed
if command -v aria2c &>/dev/null; then
  aria2_is_installed="0"
else
  aria2_is_installed="1"
  echo "aria2 not installed, installing now."
fi
if command -v 7z &>/dev/null; then
  zip_is_installed="0"
else
  zip_is_installed="1"
  echo "7z not installed, installing now."
fi
# install packages incase its not installed
if [ "$aria2_is_installed" -ne 0 ]; then
  $INSTALL_CMD aria2
fi
if [ "$zip_is_installed" -ne 0 ]; then
  $INSTALL_CMD 7zip || $INSTALL_CMD p7zip
fi

#installing vscode
$install_dir=/home/$USER/Downloads
aria2c -d "" -x 16 -s 16 -k 1M 'https://code.visualstudio.com/sha/download?build=stable&os=linux-x64'
