[config]
mode = "dark"
prefer = "saturation"

[config.wallpaper]
set = true
command = "swaybg -i {{image}} && rm ~/Wallpapers/Active/* && sleep 5 && cp '{{image}}' ~/Wallpapers/Active/current_wallpaper.png"
pre_hook = "pkill swaybg"

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.sway]
input_path = '~/.config/matugen/templates/sway-colors.conf'
output_path = '~/.config/sway/config.d/colors.conf'
post_hook = "swaymsg reload"

[templates.swayosd]
input_path = '~/.config/matugen/templates/swayosd-colors.css'
output_path = '~/.config/swayosd/colors.css'
post_hook = "pkill swayosd-server && swayosd-server &"

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'
